openapi: 3.0.0
info:
  title: User API
  version: v1
paths:
  /users:
    get:
      summary: Retrieve a list of all users.
      responses:
        '200':
          description: A list of users.
  /users/{user_id}:
    get:
      summary: Retrieve a specific user by ID.
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: A single user.
  /users/register:
    post:
      summary: Create a new user account.
      responses:
        '201':
          description: User created successfully.

